### PR TITLE
More volumes, valid articles.

### PR DESCRIPTION
**Pull request by gnott**
Resupplied content allows more volume / issue / collections to be filled in, and many previously invalid articles are now valid. Please feel free to merge if green!

### CODE REVIEW

**Comment by giorgiosironi** [comment]
504 on loading the homepage. Weird.

**Comment by giorgiosironi** [comment]
But repeatable. Something's wrong on `master` of either the formula or the project?

**Comment by gnott** [comment]
I merged new content to the `demo` project master branch yesterday (says 21 hours ago). I also deployed to the demo site, where the home page is functioning. So, maybe it indicates something about the formula or the ci environment? Maybe I'll try the tests again now for good luck, even if it is repeatable.

**Comment by gnott** [comment]
🍏

**Comment by gnott** [comment]
I'm going to merge, since it's green. I have some changes to volume 8 content including an article renumbering and I want to edit the smoke tests yet again.

**Pull request merged**
