### PR TITLE
Smoke test urls for the real volume 7, volume 8.

### PR DESCRIPTION
**Pull request by gnott**

### CODE REVIEW

**Comment by gnott** [comment]
Interesting, when I corrected one of the issue URLs, it is a `301` Moved Permanently. I wonder if that is "permanent", or it would depend on the history or state of the CI server knowing that URL once existed? Any thoughts on it @giorgiosironi?

I'll see if the smoke tests could allow `200` or `301` for that in case the status code changes unpredictably.

**Comment by gnott** [comment]
The tests say it is checking for `http://localhost:8080/collections/7-1/volume-7-1-spring-2015` but I changed this in the smoke tests, so I'm guessing it is not running the code in this PR. I'll try running the tests again.

**Comment by giorgiosironi** [comment]
>  I wonder if that is "permanent", or it would depend on the history or state of the CI server knowing that URL once existed?

There shouldn't be any state carried over between one build and another, since the server is recreated from scratch.

**Comment by giorgiosironi** [comment]
The smoke test says:
```
 GET /collections/7-1/volume-7-1-spring-2015 HTTP/1.1
...
< HTTP/1.1 301 Moved Permanently
< Location: /collections/7-1/volume-7-1-spring-2014
```
I think the slug `volume-7-1-spring-2015` is incorrect and is redirecting to the canonical one for collection `7-1`.

**Comment by gnott** [comment]
I'm not sure why a `volume-7-1-spring-2015` slug would exist in a fresh build, since I've changed it. Very strange (to me).

**Comment by giorgiosironi** [comment]
`pr-base` is using the `master` of this repository before applying the changes from this PR's branch. So if it has a slug that has been removed it will fail. At this point you can look only at `pr-fresh`, which builds from this branch only, and is green.

**Review by giorgiosironi — APPROVED** [review]

**Comment by gnott** [comment]
Ah cool, `pr-base` - noted! This should be ok to merge due to the fix I applied for that one URL, thanks  @giorgiosironi!

**Pull request merged**
