### PR TITLE
Expanded smoke test gets.

### PR DESCRIPTION
**Pull request by gnott**
An extensive list of most URLs, with two disabled for currently invalid articles. Are these too many, or when it reaches 200 article pages?

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Let's see how long it takes to execute, since there is no separate test suite I'd see no harm in running this.

**Comment by giorgiosironi** [comment]
[About 30 seconds](https://alfred.elifesciences.org/blue/organizations/jenkins/pull-requests-projects%2Fmicrosimulation-demo-formula/detail/PR-5/1/pipeline), it's a good price to pay.

**Review by giorgiosironi — APPROVED** [review]
Should I merge or wait for the other articles?

**Comment by gnott** [comment]
Ok to merge I think, I will not have complete content for many more articles today.

**Pull request merged**
