### PR TITLE
Volume 8 issue 1, is now 00109 to 00113.

### PR DESCRIPTION
**Pull request by gnott**
Article renumbering, I predict the tests on the base will fail, hopefully the tests on master will pass.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Time to re-run yet?

**Comment by gnott** [comment]
We had to re-run last time to go green as well, I expected at least 2 of 5 to pass here. Running again now to see.

**Comment by gnott** [comment]
Getting a repeatable `504` on the home page. I think we'd see at least some green here on a fresh build. Is this something else, and is it really a `Gateway timeout`, or is that related to the proxying of a `500` error? 

@giorgiosironi maybe you could take a look at the formula please to confirm at least some of these tests are starting on a fresh build?

The home page opens for me locally, and I'm pretty sure the demo site is also showing the `master` branch right now when I deployed it again about three days ago.

**Comment by giorgiosironi** [comment]
Will generate a server manually the same way the build does, and check.

**Comment by giorgiosironi** [comment]
Note that `base` seems to be broken, so it's not the changes in this formula.

**Comment by giorgiosironi** [comment]
Smoke tests pass when run manually, so we may be missing a wait condition.

**Comment by gnott** [comment]
Thanks for taking a look @giorgiosironi. I'm just testing locally before merging new content into the demo project if the home page and a few key pages are not catastrophically broken.

If you see some value in tracking down the waiting conditions for future Libero site hosting, then getting these smoke tests to pass might be valuable. For the IJM demo site itself, it might have limited value considering the current timeline.

**Comment by giorgiosironi** [comment]
I'll find out but it's in a queue of tasks, feel free to merge if it blocks you.

**Comment by gnott** [comment]
Maybe I'll merge this one for now. I already have new URLs not covered here, and I'll have even more today. I can fill out all the URLs and open a new PR later today.

**Pull request merged**
